### Practicing the Numpy einsum functionality to understand it better

In [2]:
import numpy as np

In [6]:
# Permutation of Tensors
x= np.array([[1,2,3], [4,5,6]])
print(x)

y = np.einsum('ij->ji', x)
print(y)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
# Summation
a = np.einsum("ij->",x)
print(a)

21


In [21]:
# Row sum 
b = np.einsum("ij->i", x)
print(b)
# Column Sum
c = np.einsum("ij->j", x)
print(c)



[ 6 15]
[5 7 9]


In [46]:

# Matrix-Vector Multiplication
v = np.array([2,4,8])
print(v)
d= np.einsum("ij,j->i", x, v)
print(d)

# Matrix-Matrix Multiplication
e = np.einsum("ij,jk->ik", x, y)
e = np.einsum("ij,kj->ik", x, x)
print(e)


[2 4 8]
[34 76]
[[14 32]
 [32 77]]


(3,)


In [ ]:
# Dot product first row with first row of matrix
f= np.einsum("i, i->", x[0],x[0])
print(f)

# Dot product with matrix
g = np.einsum("ij,ij->", x,x)
print(g)



14
91


In [12]:
# Hadamard Product (element-wise multiplication)
h = np.einsum("ij, ij->ij", x,x)
print(h)


[[ 1  4  9]
 [16 25 36]]


In [61]:
# Outer Product
i = np.einsum("i,j->ij", x[0],v)
print(i)


[[ 2  4  8]
 [ 4  8 16]
 [ 6 12 24]]


In [113]:

# Batch Matrix Multiplication

x= np.random.randint(low=0, high=4, size=(2,3,4))
y= np.random.randint(low=0, high=4, size=(2,4,5))
print(x.shape, y.shape)
print(x,"\n\n",y)
print("----")

j = np.einsum("ijk,ikl->ijl", x, y)
# j = np.einsum("ijk, ikj->ijk", x, y)
print(j)



(2, 3, 4) (2, 4, 5)
[[[1 2 1 1]
  [0 3 3 0]
  [2 1 1 3]]

 [[0 1 1 3]
  [3 0 3 0]
  [2 0 3 0]]] 

 [[[1 1 0 0 0]
  [1 2 0 1 0]
  [3 1 2 3 1]
  [3 2 1 3 0]]

 [[3 2 1 0 3]
  [3 0 1 3 1]
  [2 1 0 2 3]
  [3 2 2 2 2]]]
----
[[[ 9  8  3  8  1]
  [12  9  6 12  3]
  [15 11  5 13  1]]

 [[14  7  7 11 10]
  [15  9  3  6 18]
  [12  7  2  6 15]]]


In [ ]:
# j = np.einsum("ijk, ikl->ijl", x, y)
# print(j)

[[[ 28  34]
  [ 64  79]]

 [[244 268]
  [334 367]]]


In [88]:
# Matrix Diagonal
x = np.random.randint(low=0,high=5,size=(3,3))
y = np.einsum("ii->i",x)
print(x, y)

[[2 1 3]
 [1 0 3]
 [2 0 4]] [2 0 4]


In [89]:
# Matrix trace
x = np.random.randint(low=0,high=5,size=(3,3))
y = np.einsum("ii->",x)
print(x, y)

[[2 1 3]
 [4 3 3]
 [1 3 3]] 8


In [101]:
A = np.array([0, 1, 2, 3])

B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
print(A.shape, B.shape)
C = A + B
print(C)

(4,) (3, 4)
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [ ]:
(A[:, np.newaxis]* B ).sum(axis=1)

array([20, 23, 26, 29])

In [103]:
A = np.arange(6).reshape(2,3)
B = np.arange(12).reshape(3,4)+1
np.einsum('ij,jk->ki', A, B)

array([[ 23,  68],
       [ 26,  80],
       [ 29,  92],
       [ 32, 104]])

In [104]:
Ab = np.arange(6*6).reshape(6,2,3)
Bb = np.arange(6*12).reshape(6,3,4)

np.einsum("nij, njk-> nik", Ab, Bb)

array([[[  20,   23,   26,   29],
        [  56,   68,   80,   92]],

       [[ 344,  365,  386,  407],
        [ 488,  518,  548,  578]],

       [[1100, 1139, 1178, 1217],
        [1352, 1400, 1448, 1496]],

       [[2288, 2345, 2402, 2459],
        [2648, 2714, 2780, 2846]],

       [[3908, 3983, 4058, 4133],
        [4376, 4460, 4544, 4628]],

       [[5960, 6053, 6146, 6239],
        [6536, 6638, 6740, 6842]]])

array([[[  20,   23,   26,   29],
        [  56,   68,   80,   92]],

       [[ 344,  365,  386,  407],
        [ 488,  518,  548,  578]],

       [[1100, 1139, 1178, 1217],
        [1352, 1400, 1448, 1496]],

       [[2288, 2345, 2402, 2459],
        [2648, 2714, 2780, 2846]],

       [[3908, 3983, 4058, 4133],
        [4376, 4460, 4544, 4628]],

       [[5960, 6053, 6146, 6239],
        [6536, 6638, 6740, 6842]]])

### Code from Eli Bendersky's blog which translates an einsum subscript to its python string

https://eli.thegreenplace.net/2025/understanding-numpys-einsum/
https://github.com/eliben/code-for-blog/blob/main/2025/einsum-impl/impl.py

In [2]:
# Implementing the einsum function using Python code generation.
#
# Eli Bendersky (https://eli.thegreenplace.net)
# This code is in the public domain
import numpy as np


def translate_einsum(subscript):
    """Translates an explicit np.einsum subscript into Python code.

    Takes an explicit einsum subscript string and returns the string of a Python
    function that computes the same result. The function's arity matches the
    number of input parts in the subscript; for example, with 'ij,jk->ik', the
    function will have the signature:

        def calc(__a, __b):
            ... return out

    And it will calculate the matmul of __a and __b.

    This function doesn't do much error checking on the subscript; it assumes
    it's valid.
    """
    # Split inputs from output
    ins_s, out = map(str.strip, subscript.split("->"))
    inputs = list(map(str.strip, ins_s.split(",")))

    lines = []
    indent = 0

    def emit_line(line=""):
        prefix = " " * indent
        lines.append(prefix + line)

    # We have len(inputs) input arrays to the emitted function; their names
    # will be '__a', '__b', '__c', etc.
    input_names = ["__" + chr(ord("a") + i) for i in range(len(inputs))]

    emit_line(f"def calc({', '.join(input_names)}):")
    indent += 4

    # Input dimension sizes: for each input label in the subscript, create
    # a variable that holds the size of that dimension. For example, if we
    # have 'ij' for the first input, we'll create:
    #  i_size = a.shape[0]
    #  j_size = a.shape[1]
    #
    # If such a variable already exists (because the same label appears in
    # multiple inputs), we'll assert it's the same and reuse it.
    dim_sizes = set()

    for input, input_name in zip(inputs, input_names):
        for i, label in enumerate(input):
            dim_size = f"{label}_size"
            if dim_size in dim_sizes:
                emit_line(f"assert {dim_size} == {input_name}.shape[{i}]")
            else:
                emit_line(f"{dim_size} = {input_name}.shape[{i}]")
                dim_sizes.add(dim_size)

    # Output array: create a zero array of the correct shape to hold the result.
    emit_line()
    emit_line(f"out = np.zeros(({', '.join(f'{label}_size' for label in out)}))")
    emit_line()

    # Save the function-level indent level, because we'll want to come back to
    # it after emitting some number of nested loops.
    saved_indent = indent

    # Outer loops over the dimensions of the output array.
    for label in out:
        emit_line(f"for {label} in range({label}_size):")
        indent += 4

    # Create the indexing expressions for each input array and the output array.
    out_access = f"out[{', '.join(label for label in out)}]"
    in_accesses = [
        f"{input_name}[{', '.join(label for label in input)}]" for input, input_name in zip(inputs, input_names)
    ]

    # Determine if there are input dimensions that were not used in the output.
    # If so, we'll need to sum over them.
    if unused_dims := {label for label in "".join(inputs)} - set(out):
        for label in unused_dims:
            emit_line(f"for {label} in range({label}_size):")
            indent += 4

        emit_line(f"{out_access} += {' * '.join(in_accesses)}")
    else:
        # If all input dimensions are used in the output, we can just assign
        # the product directly.
        emit_line(f"{out_access} = {' * '.join(in_accesses)}")

    indent = saved_indent
    emit_line("return out")
    return "\n".join(lines)

# example usage
if __name__ == "__main__":
    A = np.arange(6).reshape(2, 3)
    B = np.arange(12).reshape(3, 4) + 1

    func_code = translate_einsum("ij,jk->ik")
    print(func_code)

    namespace = {"np": np}
    exec(func_code, namespace)
    print(namespace["calc"](A, B))

def calc(__a, __b):
    i_size = __a.shape[0]
    j_size = __a.shape[1]
    assert j_size == __b.shape[0]
    k_size = __b.shape[1]
    
    out = np.zeros((i_size, k_size))
    
    for i in range(i_size):
        for k in range(k_size):
            for j in range(j_size):
                out[i, k] += __a[i, j] * __b[j, k]
    return out
[[ 23.  26.  29.  32.]
 [ 68.  80.  92. 104.]]


In [124]:
print(translate_einsum("nij, njk-> nik"))

def calc(__a, __b):
    n_size = __a.shape[0]
    i_size = __a.shape[1]
    j_size = __a.shape[2]
    assert n_size == __b.shape[0]
    assert j_size == __b.shape[1]
    k_size = __b.shape[2]
    
    out = np.zeros((n_size, i_size, k_size))
    
    for n in range(n_size):
        for i in range(i_size):
            for k in range(k_size):
                for j in range(j_size):
                    out[n, i, k] += __a[n, i, j] * __b[n, j, k]
    return out


In [4]:
print(translate_einsum('i->'))
print(translate_einsum('i,i->i'))



def calc(__a):
    i_size = __a.shape[0]
    
    out = np.zeros(())
    
    for i in range(i_size):
        out[] += __a[i]
    return out
def calc(__a, __b):
    i_size = __a.shape[0]
    assert i_size == __b.shape[0]
    
    out = np.zeros((i_size))
    
    for i in range(i_size):
        out[i] = __a[i] * __b[i]
    return out
